services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: flavorflow
      POSTGRES_PASSWORD: flavorflow
      POSTGRES_DB: flavorflow
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
