export type Allergen =
  | 'gluten'
  | 'dairy'
  | 'nuts'
  | 'soy'
  | 'eggs'
  | 'shellfish'
  | 'fish';

export type DietaryTag =
  | 'veg'
  | 'vegan'
  | 'keto'
  | 'low-carb'
  | 'high-protein'
  | 'gluten-free';

export type MoodId =
  | 'adventurous'
  | 'comfort'
  | 'healthy'
  | 'indulgent'
  | 'spicy'
  | 'light';

export type WebMenuItem = {
  id: string;
  name: string;
  description: string;
  priceINR: number;
  veg: boolean;
  popular?: boolean;
  spiceLevel?: 0 | 1 | 2 | 3;
  calories?: number;
  allergens?: Allergen[];
  dietary?: DietaryTag[];
  imageUrl?: string;
  emoji: string;
  customizations?: { name: string; options: { label: string; deltaINR: number }[] }[];
};

export type WebReview = {
  id: string;
  user: string;
  avatarColor: string;
  rating: number;
  text: string;
  daysAgo: number;
};

export type WebRestaurant = {
  id: string;
  name: string;
  cuisines: string[];
  rating: number;
  hygieneRating: 'A+' | 'A' | 'B';
  etaMins: string;
  imageTint: string;
  coverUrl?: string;
  tags: string[];
  moods: MoodId[];
  trendingScore: number;
  liveOrders: number;
  deliveryFeeINR: number;
  distanceKm: number;
  menu: WebMenuItem[];
  reviews: WebReview[];
};

const u = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=600&auto=format&fit=crop&q=80`;

const SPICE_OPTIONS = {
  name: 'Spice level',
  options: [
    { label: 'Mild', deltaINR: 0 },
    { label: 'Medium', deltaINR: 0 },
    { label: 'Fire', deltaINR: 10 },
  ],
};

const PORTION_OPTIONS = {
  name: 'Portion',
  options: [
    { label: 'Half', deltaINR: -100 },
    { label: 'Full', deltaINR: 0 },
    { label: 'Family', deltaINR: 220 },
  ],
};

export const RESTAURANTS_WEB: WebRestaurant[] = [
  {
    id: 'r1',
    name: 'Biryani Brotherhood',
    cuisines: ['Hyderabadi', 'North Indian'],
    rating: 4.6,
    hygieneRating: 'A+',
    etaMins: '25–35 min',
    imageTint: '#7C3AED',
    coverUrl: u('1563379091339-03b21ab4a4f8'),
    tags: ['spicy', 'comfort', 'biryani'],
    moods: ['comfort', 'spicy', 'indulgent'],
    trendingScore: 92,
    liveOrders: 128,
    deliveryFeeINR: 39,
    distanceKm: 2.1,
    menu: [
      {
        id: 'm1',
        name: 'Dum Gosht Biryani',
        description: 'Slow-cooked lamb, fragrant basmati, sealed handi.',
        priceINR: 289,
        veg: false,
        popular: true,
        spiceLevel: 2,
        calories: 720,
        allergens: ['dairy'],
        dietary: ['high-protein'],
        emoji: '🍚',
        imageUrl: u('1563379091339-03b21ab4a4f8'),
        customizations: [SPICE_OPTIONS, PORTION_OPTIONS],
      },
      {
        id: 'm2',
        name: 'Subz Hyderabadi Biryani',
        description: 'Seasonal vegetables, mint, browned onions.',
        priceINR: 219,
        veg: true,
        spiceLevel: 1,
        calories: 540,
        allergens: ['dairy'],
        dietary: ['veg'],
        emoji: '🥘',
        imageUrl: u('1631292784640-2b24be784d5d'),
      },
      {
        id: 'm3',
        name: 'Mirchi Ka Salan',
        description: 'Roasted chilli peanut curry — sharp and nutty.',
        priceINR: 129,
        veg: true,
        spiceLevel: 3,
        calories: 320,
        allergens: ['nuts'],
        dietary: ['veg'],
        emoji: '🌶️',
        imageUrl: u('1565557623262-b51c2513a641'),
      },
      {
        id: 'm4',
        name: 'Chicken 65',
        description: 'Crispy fried chicken bites tossed in red chilli, curry leaves.',
        priceINR: 249,
        veg: false,
        spiceLevel: 3,
        popular: true,
        calories: 480,
        allergens: ['gluten'],
        dietary: ['high-protein'],
        emoji: '🍗',
        imageUrl: u('1626645738196-c2a7c87a8f3a'),
      },
      {
        id: 'm5',
        name: 'Double Ka Meetha',
        description: 'Saffron bread pudding, cardamom syrup, pistachio.',
        priceINR: 179,
        veg: true,
        calories: 420,
        allergens: ['dairy', 'nuts', 'gluten'],
        dietary: ['veg'],
        emoji: '🍮',
        imageUrl: u('1551024601-bec78aea704b'),
      },
    ],
    reviews: [
      {
        id: 'rv1',
        user: 'Aarav M.',
        avatarColor: '#F59E0B',
        rating: 5,
        text: 'Smoky, juicy lamb, perfect rice texture. Repeat order incoming.',
        daysAgo: 2,
      },
      {
        id: 'rv2',
        user: 'Riya K.',
        avatarColor: '#EC4899',
        rating: 4,
        text: 'Loved the salan. Biryani was a touch oily but still great.',
        daysAgo: 5,
      },
    ],
  },
  {
    id: 'r2',
    name: 'Neon Slice Lab',
    cuisines: ['Pizza', 'Italian'],
    rating: 4.4,
    hygieneRating: 'A',
    etaMins: '30–40 min',
    imageTint: '#F97316',
    coverUrl: u('1565299624946-b28f40a0ae38'),
    tags: ['cheesy', 'late-night', 'pizza'],
    moods: ['indulgent', 'comfort'],
    trendingScore: 88,
    liveOrders: 96,
    deliveryFeeINR: 49,
    distanceKm: 3.4,
    menu: [
      {
        id: 'm10',
        name: 'Charred Pepperoni Pizza',
        description: 'San Marzano, fior di latte, cup-and-char pepperoni.',
        priceINR: 349,
        veg: false,
        popular: true,
        spiceLevel: 1,
        calories: 880,
        allergens: ['gluten', 'dairy'],
        dietary: ['high-protein'],
        emoji: '🍕',
        imageUrl: u('1565299624946-b28f40a0ae38'),
      },
      {
        id: 'm11',
        name: 'Wild Mushroom Pizza',
        description: 'Truffle oil, taleggio, thyme, on a slow-fermented base.',
        priceINR: 379,
        veg: true,
        calories: 760,
        allergens: ['gluten', 'dairy'],
        dietary: ['veg'],
        emoji: '🍕',
        imageUrl: u('1571066811602-716837d681de'),
      },
      {
        id: 'm12',
        name: 'Margherita Classico',
        description: 'Buffalo mozzarella, fresh basil, slow San Marzano sauce.',
        priceINR: 299,
        veg: true,
        calories: 700,
        allergens: ['gluten', 'dairy'],
        dietary: ['veg'],
        emoji: '🍕',
        imageUrl: u('1574071318508-1cdbab80d002'),
      },
      {
        id: 'm13',
        name: 'Diavolo Inferno Pizza',
        description: 'Spicy salami, scotch bonnet honey, jalapeños — bring napkins.',
        priceINR: 389,
        veg: false,
        spiceLevel: 3,
        popular: true,
        calories: 920,
        allergens: ['gluten', 'dairy'],
        dietary: ['high-protein'],
        emoji: '🌶️',
        imageUrl: u('1593504049359-74330189a345'),
      },
      {
        id: 'm14',
        name: 'Garlic Knots',
        description: 'Hand-knotted, sea-salt, parsley butter.',
        priceINR: 149,
        veg: true,
        spiceLevel: 0,
        calories: 320,
        allergens: ['gluten', 'dairy'],
        dietary: ['veg'],
        emoji: '🥖',
        imageUrl: u('1573140247632-f8fd74997d5c'),
      },
    ],
    reviews: [
      {
        id: 'rv3',
        user: 'Kabir D.',
        avatarColor: '#0EA5E9',
        rating: 5,
        text: 'Crust to die for. Knots are basically an addiction.',
        daysAgo: 1,
      },
    ],
  },
  {
    id: 'r3',
    name: 'Pasta Lab Co.',
    cuisines: ['Italian', 'Pasta'],
    rating: 4.7,
    hygieneRating: 'A+',
    etaMins: '25–35 min',
    imageTint: '#EAB308',
    coverUrl: u('1551183053-bf91a1d81141'),
    tags: ['pasta', 'comfort', 'date-night'],
    moods: ['comfort', 'indulgent'],
    trendingScore: 90,
    liveOrders: 84,
    deliveryFeeINR: 35,
    distanceKm: 1.8,
    menu: [
      {
        id: 'm20',
        name: 'Penne Arrabbiata',
        description: 'Classic spicy tomato, garlic, red chilli, parsley.',
        priceINR: 269,
        veg: true,
        spiceLevel: 3,
        popular: true,
        calories: 580,
        allergens: ['gluten'],
        dietary: ['veg'],
        emoji: '🍝',
        imageUrl: u('1608897013039-887f21d8c804'),
      },
      {
        id: 'm21',
        name: 'Truffle Carbonara',
        description: 'Guanciale, pecorino, egg yolk, shaved black truffle.',
        priceINR: 429,
        veg: false,
        calories: 720,
        allergens: ['gluten', 'dairy', 'eggs'],
        dietary: ['high-protein'],
        emoji: '🍝',
        imageUrl: u('1551183053-bf91a1d81141'),
      },
      {
        id: 'm22',
        name: 'Spicy Prawn Aglio Olio',
        description: 'Chilli oil, garlic, prawns, lemon zest.',
        priceINR: 379,
        veg: false,
        spiceLevel: 2,
        popular: true,
        calories: 540,
        allergens: ['gluten', 'shellfish'],
        dietary: ['high-protein'],
        emoji: '🍤',
        imageUrl: u('1576007473554-6e1b8f8f5a6e'),
      },
      {
        id: 'm23',
        name: 'Spinach & Ricotta Ravioli',
        description: 'Hand-folded ravioli, sage butter, parmesan crisp.',
        priceINR: 349,
        veg: true,
        calories: 510,
        allergens: ['gluten', 'dairy', 'eggs'],
        dietary: ['veg'],
        emoji: '🥟',
        imageUrl: u('1587740908075-9e245070dfaa'),
      },
      {
        id: 'm24',
        name: 'Tiramisu',
        description: 'Mascarpone, espresso-soaked savoiardi, cocoa dust.',
        priceINR: 199,
        veg: true,
        calories: 410,
        allergens: ['gluten', 'dairy', 'eggs'],
        dietary: ['veg'],
        emoji: '🍰',
        imageUrl: u('1571877227200-a0d98ea607e9'),
      },
    ],
    reviews: [
      {
        id: 'rv4',
        user: 'Mira S.',
        avatarColor: '#22C55E',
        rating: 5,
        text: 'The arrabbiata has actual heat — finally a proper spicy pasta.',
        daysAgo: 3,
      },
    ],
  },
  {
    id: 'r4',
    name: 'Sakura Bowls',
    cuisines: ['Japanese', 'Healthy'],
    rating: 4.7,
    hygieneRating: 'A+',
    etaMins: '20–30 min',
    imageTint: '#0EA5E9',
    coverUrl: u('1559847844-5315695dadae'),
    tags: ['healthy', 'low-oil', 'sushi', 'ramen'],
    moods: ['healthy', 'light', 'adventurous'],
    trendingScore: 81,
    liveOrders: 64,
    deliveryFeeINR: 29,
    distanceKm: 1.6,
    menu: [
      {
        id: 'm30',
        name: 'Salmon Aburi Bowl',
        description: 'Torched salmon, miso barley, pickles, sesame crunch.',
        priceINR: 399,
        veg: false,
        popular: true,
        calories: 510,
        allergens: ['soy', 'fish'],
        dietary: ['high-protein', 'low-carb'],
        emoji: '🍣',
        imageUrl: u('1559847844-5315695dadae'),
      },
      {
        id: 'm31',
        name: 'Tonkotsu Ramen',
        description: '14-hour pork bone broth, chashu, ajitsuke tamago.',
        priceINR: 379,
        veg: false,
        popular: true,
        calories: 660,
        allergens: ['gluten', 'soy', 'eggs'],
        dietary: ['high-protein'],
        emoji: '🍜',
        imageUrl: u('1623341214825-9f4f963727da'),
      },
      {
        id: 'm32',
        name: 'Spicy Tuna Roll',
        description: 'Yellowfin, sriracha mayo, scallions, tobiko.',
        priceINR: 329,
        veg: false,
        spiceLevel: 2,
        calories: 380,
        allergens: ['fish', 'soy', 'eggs'],
        dietary: ['high-protein'],
        emoji: '🍱',
        imageUrl: u('1579871494447-9811cf80d66c'),
      },
      {
        id: 'm33',
        name: 'Tofu Katsu Curry',
        description: 'Panko tofu, heirloom carrots, short grain rice.',
        priceINR: 279,
        veg: true,
        calories: 620,
        allergens: ['soy', 'gluten'],
        dietary: ['veg'],
        emoji: '🍛',
        imageUrl: u('1565280654-9d2bc62fa07d'),
      },
      {
        id: 'm34',
        name: 'Edamame & Sea Salt',
        description: 'Steamed pods, smoked salt flakes.',
        priceINR: 119,
        veg: true,
        calories: 180,
        dietary: ['veg', 'vegan', 'gluten-free', 'high-protein'],
        emoji: '🫛',
        imageUrl: u('1622097506873-46a4d9a8f9e5'),
      },
    ],
    reviews: [
      {
        id: 'rv5',
        user: 'Mira S.',
        avatarColor: '#22C55E',
        rating: 5,
        text: 'Light but satisfying — exactly what post-yoga lunch should be.',
        daysAgo: 3,
      },
    ],
  },
  {
    id: 'r5',
    name: 'Cantina Roja',
    cuisines: ['Mexican', 'Tex-Mex'],
    rating: 4.5,
    hygieneRating: 'A',
    etaMins: '25–35 min',
    imageTint: '#F43F5E',
    coverUrl: u('1565299585323-38d6b0865b47'),
    tags: ['spicy', 'tacos', 'street-food'],
    moods: ['spicy', 'adventurous', 'indulgent'],
    trendingScore: 85,
    liveOrders: 73,
    deliveryFeeINR: 39,
    distanceKm: 2.6,
    menu: [
      {
        id: 'm40',
        name: 'Carne Asada Tacos',
        description: 'Charred steak, salsa verde, pickled onion, cilantro.',
        priceINR: 299,
        veg: false,
        popular: true,
        spiceLevel: 2,
        calories: 540,
        allergens: ['gluten', 'dairy'],
        dietary: ['high-protein'],
        emoji: '🌮',
        imageUrl: u('1565299585323-38d6b0865b47'),
      },
      {
        id: 'm41',
        name: 'Chicken Quesadilla',
        description: 'Smoked chicken, oaxaca cheese, charred peppers.',
        priceINR: 269,
        veg: false,
        spiceLevel: 1,
        calories: 580,
        allergens: ['gluten', 'dairy'],
        dietary: ['high-protein'],
        emoji: '🫓',
        imageUrl: u('1599974579688-8dbdd335c77f'),
      },
      {
        id: 'm42',
        name: 'Burrito Bowl',
        description: 'Cilantro rice, black beans, chipotle chicken, guac.',
        priceINR: 319,
        veg: false,
        spiceLevel: 1,
        calories: 720,
        allergens: ['dairy'],
        dietary: ['high-protein', 'gluten-free'],
        emoji: '🥙',
        imageUrl: u('1626700051175-6818013e1d4f'),
      },
      {
        id: 'm43',
        name: 'Spicy Diablo Tacos',
        description: 'Habanero pulled pork, mango salsa, lime crema.',
        priceINR: 329,
        veg: false,
        spiceLevel: 3,
        popular: true,
        calories: 560,
        allergens: ['gluten', 'dairy'],
        dietary: ['high-protein'],
        emoji: '🌶️',
        imageUrl: u('1551504734-5ee1c4a1479b'),
      },
      {
        id: 'm44',
        name: 'Guacamole & Chips',
        description: 'Hand-mashed avo, lime, jalapeño, blue corn chips.',
        priceINR: 199,
        veg: true,
        spiceLevel: 1,
        calories: 380,
        allergens: [],
        dietary: ['veg', 'vegan', 'gluten-free'],
        emoji: '🥑',
        imageUrl: u('1604329760661-e71dc83f8f26'),
      },
      {
        id: 'm45',
        name: 'Churros con Chocolate',
        description: 'Cinnamon sugar, dark Mexican chocolate dip.',
        priceINR: 189,
        veg: true,
        calories: 460,
        allergens: ['gluten', 'dairy', 'eggs'],
        dietary: ['veg'],
        emoji: '🍩',
        imageUrl: u('1639744093327-e5fe0a59b5cf'),
      },
    ],
    reviews: [
      {
        id: 'rv6',
        user: 'Zara P.',
        avatarColor: '#A855F7',
        rating: 5,
        text: 'Diablo tacos are not a joke. Bring milk.',
        daysAgo: 4,
      },
    ],
  },
  {
    id: 'r6',
    name: 'Seoul Spice',
    cuisines: ['Korean', 'BBQ'],
    rating: 4.6,
    hygieneRating: 'A+',
    etaMins: '28–38 min',
    imageTint: '#DC2626',
    coverUrl: u('1583224964978-2257b960c3d3'),
    tags: ['spicy', 'kimchi', 'rice bowl'],
    moods: ['spicy', 'adventurous', 'comfort'],
    trendingScore: 82,
    liveOrders: 58,
    deliveryFeeINR: 39,
    distanceKm: 3.0,
    menu: [
      {
        id: 'm50',
        name: 'Bibimbap Bowl',
        description: 'Steamed rice, sautéed veg, gochujang, sunny egg.',
        priceINR: 319,
        veg: false,
        spiceLevel: 2,
        popular: true,
        calories: 620,
        allergens: ['soy', 'eggs'],
        dietary: ['high-protein'],
        emoji: '🍱',
        imageUrl: u('1593560708920-61dd98c46a4e'),
      },
      {
        id: 'm51',
        name: 'Korean Fried Chicken',
        description: 'Double-fried, gochujang glaze, sesame, scallion.',
        priceINR: 379,
        veg: false,
        popular: true,
        spiceLevel: 2,
        calories: 740,
        allergens: ['gluten', 'soy'],
        dietary: ['high-protein'],
        emoji: '🍗',
        imageUrl: u('1626082935054-2c5dfd1e6d7a'),
      },
      {
        id: 'm52',
        name: 'Bulgogi Beef',
        description: 'Marinated rib-eye, lettuce wraps, ssamjang.',
        priceINR: 419,
        veg: false,
        spiceLevel: 1,
        calories: 580,
        allergens: ['soy'],
        dietary: ['high-protein', 'gluten-free'],
        emoji: '🥩',
        imageUrl: u('1583224994076-ae7b3ed9fdd3'),
      },
      {
        id: 'm53',
        name: 'Tteokbokki Inferno',
        description: 'Rice cakes, fish cake, fire-grade gochujang.',
        priceINR: 299,
        veg: false,
        spiceLevel: 3,
        calories: 560,
        allergens: ['soy', 'fish', 'gluten'],
        dietary: ['high-protein'],
        emoji: '🌶️',
        imageUrl: u('1635363638580-c2809d049eee'),
      },
      {
        id: 'm54',
        name: 'Kimchi Pancake',
        description: 'Crispy buchimgae, aged kimchi, soy-vinegar dip.',
        priceINR: 229,
        veg: true,
        spiceLevel: 1,
        calories: 410,
        allergens: ['soy', 'gluten', 'eggs'],
        dietary: ['veg'],
        emoji: '🥞',
        imageUrl: u('1576092762791-dd9e2220abd1'),
      },
    ],
    reviews: [
      {
        id: 'rv7',
        user: 'Hana L.',
        avatarColor: '#EF4444',
        rating: 5,
        text: 'Tteokbokki cleared my sinuses. Worth it.',
        daysAgo: 2,
      },
    ],
  },
  {
    id: 'r7',
    name: 'Bangkok Street',
    cuisines: ['Thai', 'Street food'],
    rating: 4.5,
    hygieneRating: 'A',
    etaMins: '25–35 min',
    imageTint: '#10B981',
    coverUrl: u('1559314809-0d155014e29e'),
    tags: ['spicy', 'noodles', 'curry'],
    moods: ['spicy', 'adventurous', 'comfort'],
    trendingScore: 78,
    liveOrders: 51,
    deliveryFeeINR: 35,
    distanceKm: 2.3,
    menu: [
      {
        id: 'm60',
        name: 'Pad Thai Prawn',
        description: 'Wok-tossed rice noodles, tamarind, peanuts, lime.',
        priceINR: 339,
        veg: false,
        popular: true,
        spiceLevel: 1,
        calories: 580,
        allergens: ['gluten', 'shellfish', 'nuts', 'eggs', 'soy'],
        dietary: ['high-protein'],
        emoji: '🍜',
        imageUrl: u('1559314809-0d155014e29e'),
      },
      {
        id: 'm61',
        name: 'Green Curry Chicken',
        description: 'Coconut, kaffir lime, basil, jasmine rice.',
        priceINR: 319,
        veg: false,
        spiceLevel: 2,
        calories: 540,
        allergens: ['fish', 'soy'],
        dietary: ['high-protein', 'gluten-free'],
        emoji: '🥘',
        imageUrl: u('1572455024541-c9b0c7c87a1e'),
      },
      {
        id: 'm62',
        name: 'Tom Yum Goong',
        description: 'Hot & sour broth, prawns, lemongrass, galangal.',
        priceINR: 289,
        veg: false,
        spiceLevel: 3,
        calories: 320,
        allergens: ['shellfish', 'fish'],
        dietary: ['high-protein', 'gluten-free'],
        emoji: '🍲',
        imageUrl: u('1569058242253-92a9c755a0ec'),
      },
      {
        id: 'm63',
        name: 'Drunken Noodles',
        description: 'Wide rice noodles, holy basil, bird chilli, soy.',
        priceINR: 309,
        veg: false,
        spiceLevel: 3,
        popular: true,
        calories: 600,
        allergens: ['gluten', 'soy'],
        dietary: ['high-protein'],
        emoji: '🌶️',
        imageUrl: u('1552611052-33e04de081de'),
      },
      {
        id: 'm64',
        name: 'Mango Sticky Rice',
        description: 'Coconut sweet rice, ataulfo mango, sesame.',
        priceINR: 219,
        veg: true,
        calories: 380,
        allergens: [],
        dietary: ['veg', 'vegan', 'gluten-free'],
        emoji: '🥭',
        imageUrl: u('1626700051125-6818013e1d4f'),
      },
    ],
    reviews: [],
  },
  {
    id: 'r8',
    name: 'Smash & Sip',
    cuisines: ['American', 'Burgers'],
    rating: 4.4,
    hygieneRating: 'A',
    etaMins: '20–30 min',
    imageTint: '#F59E0B',
    coverUrl: u('1568901346375-23c9450c58cd'),
    tags: ['burger', 'comfort', 'late-night'],
    moods: ['comfort', 'indulgent'],
    trendingScore: 80,
    liveOrders: 67,
    deliveryFeeINR: 39,
    distanceKm: 2.8,
    menu: [
      {
        id: 'm70',
        name: 'Classic Smash Burger',
        description: 'Double smash patty, american cheese, special sauce.',
        priceINR: 299,
        veg: false,
        popular: true,
        calories: 720,
        allergens: ['gluten', 'dairy', 'eggs'],
        dietary: ['high-protein'],
        emoji: '🍔',
        imageUrl: u('1568901346375-23c9450c58cd'),
      },
      {
        id: 'm71',
        name: 'Spicy Buffalo Burger',
        description: 'Crispy chicken, blue cheese, hot sauce, slaw.',
        priceINR: 329,
        veg: false,
        spiceLevel: 2,
        calories: 760,
        allergens: ['gluten', 'dairy'],
        dietary: ['high-protein'],
        emoji: '🍔',
        imageUrl: u('1571091655789-405eb7a3a3a8'),
      },
      {
        id: 'm72',
        name: 'Paneer Tikka Burger',
        description: 'Tandoor paneer patty, mint mayo, pickled onion.',
        priceINR: 269,
        veg: true,
        spiceLevel: 1,
        calories: 640,
        allergens: ['gluten', 'dairy'],
        dietary: ['veg', 'high-protein'],
        emoji: '🍔',
        imageUrl: u('1607013251379-e6eecfffe234'),
      },
      {
        id: 'm73',
        name: 'Loaded Buffalo Wings',
        description: 'Hot sauce, blue cheese drizzle, celery sticks.',
        priceINR: 289,
        veg: false,
        spiceLevel: 3,
        popular: true,
        calories: 620,
        allergens: ['dairy'],
        dietary: ['high-protein'],
        emoji: '🍗',
        imageUrl: u('1567620832903-9fc6debc209f'),
      },
      {
        id: 'm74',
        name: 'Truffle Parmesan Fries',
        description: 'Crispy fries, truffle oil, micro parsley, parm.',
        priceINR: 179,
        veg: true,
        calories: 480,
        allergens: ['dairy'],
        dietary: ['veg'],
        emoji: '🍟',
        imageUrl: u('1573080496219-bb080dd4f877'),
      },
      {
        id: 'm75',
        name: 'Oreo Thick Shake',
        description: 'Vanilla soft serve, oreo crumble, chocolate drizzle.',
        priceINR: 199,
        veg: true,
        calories: 540,
        allergens: ['dairy', 'gluten'],
        dietary: ['veg'],
        emoji: '🥤',
        imageUrl: u('1572490122747-3968b75cc699'),
      },
    ],
    reviews: [],
  },
  {
    id: 'r9',
    name: 'Levantine Light',
    cuisines: ['Middle Eastern', 'Mezze'],
    rating: 4.5,
    hygieneRating: 'A+',
    etaMins: '25–35 min',
    imageTint: '#EAB308',
    coverUrl: u('1561651823-34feb02250e4'),
    tags: ['shawarma', 'healthy', 'mezze'],
    moods: ['healthy', 'adventurous', 'light'],
    trendingScore: 73,
    liveOrders: 41,
    deliveryFeeINR: 35,
    distanceKm: 2.4,
    menu: [
      {
        id: 'm80',
        name: 'Lamb Shawarma Wrap',
        description: 'Spit-roasted lamb, garlic toum, pickled turnip.',
        priceINR: 319,
        veg: false,
        popular: true,
        spiceLevel: 1,
        calories: 580,
        allergens: ['gluten', 'dairy'],
        dietary: ['high-protein'],
        emoji: '🌯',
        imageUrl: u('1561651823-34feb02250e4'),
      },
      {
        id: 'm81',
        name: 'Falafel & Tahini Bowl',
        description: 'Crispy falafel, beetroot hummus, herby grains.',
        priceINR: 269,
        veg: true,
        calories: 540,
        allergens: ['gluten', 'soy'],
        dietary: ['veg', 'vegan', 'high-protein'],
        emoji: '🧆',
        imageUrl: u('1593504049359-74330189a345'),
      },
      {
        id: 'm82',
        name: 'Hummus Trio & Pita',
        description: 'Classic, beetroot, harissa hummus, warm pita.',
        priceINR: 229,
        veg: true,
        calories: 480,
        allergens: ['gluten'],
        dietary: ['veg', 'vegan'],
        emoji: '🥙',
        imageUrl: u('1577805947697-89e18249d767'),
      },
      {
        id: 'm83',
        name: 'Spicy Harissa Chicken Kebab',
        description: 'Charcoal-grilled, harissa, sumac slaw.',
        priceINR: 349,
        veg: false,
        spiceLevel: 2,
        calories: 520,
        allergens: ['dairy'],
        dietary: ['high-protein', 'gluten-free'],
        emoji: '🍢',
        imageUrl: u('1599487488170-d11ec9c172f0'),
      },
      {
        id: 'm84',
        name: 'Baklava',
        description: 'Phyllo, pistachio, rosewater syrup.',
        priceINR: 169,
        veg: true,
        calories: 410,
        allergens: ['gluten', 'nuts', 'dairy'],
        dietary: ['veg'],
        emoji: '🍯',
        imageUrl: u('1602080858428-57174f9431cf'),
      },
    ],
    reviews: [],
  },
  {
    id: 'r10',
    name: 'Wok Royale',
    cuisines: ['Chinese', 'Pan-Asian'],
    rating: 4.3,
    hygieneRating: 'A',
    etaMins: '25–35 min',
    imageTint: '#F97316',
    coverUrl: u('1585032226651-759b368d7246'),
    tags: ['noodles', 'spicy', 'comfort'],
    moods: ['comfort', 'indulgent', 'spicy'],
    trendingScore: 76,
    liveOrders: 49,
    deliveryFeeINR: 35,
    distanceKm: 2.0,
    menu: [
      {
        id: 'm90',
        name: 'Hakka Noodles',
        description: 'Wok-tossed noodles, sesame oil, fresh greens.',
        priceINR: 219,
        veg: true,
        spiceLevel: 1,
        popular: true,
        calories: 540,
        allergens: ['gluten', 'soy'],
        dietary: ['veg'],
        emoji: '🍜',
        imageUrl: u('1585032226651-759b368d7246'),
      },
      {
        id: 'm91',
        name: 'Schezwan Manchurian',
        description: 'Cabbage dumplings, scotch bonnet schezwan glaze.',
        priceINR: 249,
        veg: true,
        spiceLevel: 3,
        popular: true,
        calories: 580,
        allergens: ['gluten', 'soy'],
        dietary: ['veg'],
        emoji: '🌶️',
        imageUrl: u('1606471191009-63994c53433b'),
      },
      {
        id: 'm92',
        name: 'Sweet & Sour Chicken',
        description: 'Pineapple, bell pepper, gochu glaze, jasmine rice.',
        priceINR: 299,
        veg: false,
        spiceLevel: 1,
        calories: 660,
        allergens: ['gluten', 'soy', 'eggs'],
        dietary: ['high-protein'],
        emoji: '🍛',
        imageUrl: u('1582450871972-ab5ca641643d'),
      },
      {
        id: 'm93',
        name: 'Honey Chilli Lotus Stem',
        description: 'Crispy lotus, sesame, honey-chilli toss.',
        priceINR: 269,
        veg: true,
        spiceLevel: 2,
        calories: 480,
        allergens: ['gluten', 'soy'],
        dietary: ['veg'],
        emoji: '🍯',
        imageUrl: u('1626700051125-6818013e1d4f'),
      },
      {
        id: 'm94',
        name: 'Fortune Cookies',
        description: 'Crisp, sweet, with a punchline inside.',
        priceINR: 99,
        veg: true,
        calories: 180,
        allergens: ['gluten', 'eggs'],
        dietary: ['veg'],
        emoji: '🥠',
        imageUrl: u('1571805341302-f857810196ce'),
      },
    ],
    reviews: [],
  },
  {
    id: 'r11',
    name: 'Greens & Grains',
    cuisines: ['Healthy', 'Salads'],
    rating: 4.6,
    hygieneRating: 'A+',
    etaMins: '18–28 min',
    imageTint: '#84CC16',
    coverUrl: u('1546069901-ba9599a7e63c'),
    tags: ['healthy', 'low-cal', 'fresh'],
    moods: ['healthy', 'light'],
    trendingScore: 71,
    liveOrders: 38,
    deliveryFeeINR: 25,
    distanceKm: 1.4,
    menu: [
      {
        id: 'm100',
        name: 'Quinoa Buddha Bowl',
        description: 'Quinoa, roast beets, kale, tahini drizzle.',
        priceINR: 289,
        veg: true,
        calories: 480,
        allergens: ['soy'],
        dietary: ['veg', 'vegan', 'high-protein', 'gluten-free'],
        emoji: '🥗',
        imageUrl: u('1546069901-ba9599a7e63c'),
      },
      {
        id: 'm101',
        name: 'Avocado Caesar',
        description: 'Romaine, kale, avocado, crispy chickpeas, parm.',
        priceINR: 269,
        veg: true,
        calories: 420,
        allergens: ['dairy', 'gluten', 'eggs'],
        dietary: ['veg'],
        emoji: '🥑',
        imageUrl: u('1505253716362-afaea1d3d1af'),
      },
      {
        id: 'm102',
        name: 'Açaí Power Bowl',
        description: 'Açaí, banana, granola, almond butter, berries.',
        priceINR: 249,
        veg: true,
        calories: 380,
        allergens: ['nuts', 'gluten'],
        dietary: ['veg', 'vegan', 'high-protein'],
        emoji: '🍓',
        imageUrl: u('1543339308-43e59d6b73a6'),
      },
      {
        id: 'm103',
        name: 'Spicy Peanut Soba',
        description: 'Cold soba, cucumber, scallion, chilli peanut sauce.',
        priceINR: 279,
        veg: true,
        spiceLevel: 2,
        calories: 460,
        allergens: ['gluten', 'nuts', 'soy'],
        dietary: ['veg', 'vegan', 'high-protein'],
        emoji: '🥬',
        imageUrl: u('1517423440428-a5a00ad493e8'),
      },
      {
        id: 'm104',
        name: 'Cold-Pressed Green Juice',
        description: 'Spinach, apple, cucumber, ginger, lemon.',
        priceINR: 159,
        veg: true,
        calories: 110,
        allergens: [],
        dietary: ['veg', 'vegan', 'gluten-free'],
        emoji: '🥒',
        imageUrl: u('1622597468961-2c9e7e1e6b1f'),
      },
    ],
    reviews: [],
  },
  {
    id: 'r12',
    name: 'Saigon Banh Mi',
    cuisines: ['Vietnamese', 'Sandwiches'],
    rating: 4.5,
    hygieneRating: 'A',
    etaMins: '18–28 min',
    imageTint: '#F472B6',
    coverUrl: u('1612927601601-6638404737ce'),
    tags: ['fresh', 'spicy', 'street'],
    moods: ['adventurous', 'light', 'spicy'],
    trendingScore: 70,
    liveOrders: 42,
    deliveryFeeINR: 35,
    distanceKm: 2.8,
    menu: [
      {
        id: 'm110',
        name: 'Lemongrass Pork Banh Mi',
        description: 'Pickled daikon, cilantro, chili mayo, baguette.',
        priceINR: 269,
        veg: false,
        popular: true,
        spiceLevel: 2,
        calories: 590,
        allergens: ['gluten', 'eggs'],
        dietary: ['high-protein'],
        emoji: '🥖',
        imageUrl: u('1601314167846-95e7d8c10cda'),
      },
      {
        id: 'm111',
        name: 'Beef Pho',
        description: 'Five-hour broth, rice noodles, fresh herbs, lime.',
        priceINR: 329,
        veg: false,
        spiceLevel: 1,
        calories: 480,
        allergens: ['soy'],
        dietary: ['high-protein', 'gluten-free'],
        emoji: '🍲',
        imageUrl: u('1612927601601-6638404737ce'),
      },
      {
        id: 'm112',
        name: 'Summer Rolls',
        description: 'Rice paper, prawn, mint, peanut hoisin dip.',
        priceINR: 219,
        veg: false,
        calories: 280,
        allergens: ['shellfish', 'nuts', 'soy'],
        dietary: ['high-protein', 'gluten-free'],
        emoji: '🌯',
        imageUrl: u('1606470010023-78c1f5b2b2a4'),
      },
      {
        id: 'm113',
        name: 'Mushroom Pho (Vegan)',
        description: 'Five-spice broth, rice noodles, shiitake.',
        priceINR: 289,
        veg: true,
        calories: 420,
        allergens: ['soy'],
        dietary: ['veg', 'vegan'],
        emoji: '🍜',
        imageUrl: u('1583394293214-28a4b1a5b1e9'),
      },
    ],
    reviews: [],
  },
  {
    id: 'r13',
    name: 'Midnight Dosai Co.',
    cuisines: ['South Indian', 'Street food'],
    rating: 4.5,
    hygieneRating: 'A',
    etaMins: '15–25 min',
    imageTint: '#10B981',
    coverUrl: u('1668236543090-82eba5ee5976'),
    tags: ['veg', 'comfort', 'quick', 'dosa'],
    moods: ['comfort', 'spicy'],
    trendingScore: 75,
    liveOrders: 53,
    deliveryFeeINR: 19,
    distanceKm: 0.9,
    menu: [
      {
        id: 'm120',
        name: 'Podi Molaga Dosa',
        description: 'Ghee-roasted millet dosa, gunpowder chutney.',
        priceINR: 149,
        veg: true,
        popular: true,
        spiceLevel: 2,
        calories: 480,
        allergens: ['dairy'],
        dietary: ['veg'],
        emoji: '🫓',
        imageUrl: u('1668236543090-82eba5ee5976'),
      },
      {
        id: 'm121',
        name: 'Idli & Sambar',
        description: 'Steamed lentil cakes, peppery sambar, three chutneys.',
        priceINR: 119,
        veg: true,
        spiceLevel: 1,
        calories: 320,
        allergens: [],
        dietary: ['veg', 'vegan', 'gluten-free'],
        emoji: '🥟',
        imageUrl: u('1631292784640-2b24be784d5d'),
      },
      {
        id: 'm122',
        name: 'Vada Pav',
        description: 'Spiced potato vada, garlic chutney, soft pav.',
        priceINR: 89,
        veg: true,
        spiceLevel: 2,
        calories: 360,
        allergens: ['gluten'],
        dietary: ['veg', 'vegan'],
        emoji: '🍔',
        imageUrl: u('1606471191009-63994c53433b'),
      },
      {
        id: 'm123',
        name: 'Filter Kaapi Float',
        description: 'Cold brew jaggery filter coffee, vanilla foam.',
        priceINR: 99,
        veg: true,
        calories: 180,
        allergens: ['dairy'],
        dietary: ['veg'],
        emoji: '☕',
        imageUrl: u('1495474472287-4d71bcdd2085'),
      },
    ],
    reviews: [],
  },
  {
    id: 'r14',
    name: 'Maple & Oats',
    cuisines: ['Breakfast', 'Brunch'],
    rating: 4.3,
    hygieneRating: 'A+',
    etaMins: '20–30 min',
    imageTint: '#FBBF24',
    coverUrl: u('1567620905732-2d1ec7ab7445'),
    tags: ['cozy', 'healthy', 'brunch'],
    moods: ['comfort', 'healthy', 'light'],
    trendingScore: 64,
    liveOrders: 37,
    deliveryFeeINR: 25,
    distanceKm: 1.2,
    menu: [
      {
        id: 'm130',
        name: 'Brown Butter Pancakes',
        description: 'Maple, candied pecans, crème fraîche.',
        priceINR: 269,
        veg: true,
        popular: true,
        calories: 740,
        allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
        dietary: ['veg'],
        emoji: '🥞',
        imageUrl: u('1567620905732-2d1ec7ab7445'),
      },
      {
        id: 'm131',
        name: 'Avocado Sourdough',
        description: 'Smashed avo, chili crisp, poached egg.',
        priceINR: 319,
        veg: false,
        spiceLevel: 1,
        calories: 510,
        allergens: ['gluten', 'eggs'],
        dietary: ['high-protein'],
        emoji: '🥑',
        imageUrl: u('1525351484163-7529414344d8'),
      },
      {
        id: 'm132',
        name: 'Eggs Benedict',
        description: 'English muffin, hollandaise, smoked salmon.',
        priceINR: 369,
        veg: false,
        calories: 580,
        allergens: ['gluten', 'eggs', 'dairy', 'fish'],
        dietary: ['high-protein'],
        emoji: '🍳',
        imageUrl: u('1607301406259-dfb186e15de8'),
      },
      {
        id: 'm133',
        name: 'Belgian Waffles',
        description: 'Crispy waffles, berries, maple butter.',
        priceINR: 249,
        veg: true,
        calories: 620,
        allergens: ['gluten', 'dairy', 'eggs'],
        dietary: ['veg'],
        emoji: '🧇',
        imageUrl: u('1562376552-0d160a2f238d'),
      },
    ],
    reviews: [],
  },
  {
    id: 'r15',
    name: 'Sweet Spot Bakery',
    cuisines: ['Desserts', 'Bakery'],
    rating: 4.7,
    hygieneRating: 'A+',
    etaMins: '20–30 min',
    imageTint: '#EC4899',
    coverUrl: u('1551024601-bec78aea704b'),
    tags: ['sweet', 'late-night'],
    moods: ['indulgent', 'comfort'],
    trendingScore: 79,
    liveOrders: 44,
    deliveryFeeINR: 29,
    distanceKm: 1.5,
    menu: [
      {
        id: 'm140',
        name: 'Molten Chocolate Lava',
        description: 'Belgian chocolate centre, vanilla bean ice cream.',
        priceINR: 229,
        veg: true,
        popular: true,
        calories: 540,
        allergens: ['gluten', 'dairy', 'eggs'],
        dietary: ['veg'],
        emoji: '🍫',
        imageUrl: u('1606313564200-e75d5e30476c'),
      },
      {
        id: 'm141',
        name: 'Cinnamon Roll',
        description: 'Warm brioche roll, cream cheese frosting.',
        priceINR: 169,
        veg: true,
        calories: 460,
        allergens: ['gluten', 'dairy', 'eggs'],
        dietary: ['veg'],
        emoji: '🥐',
        imageUrl: u('1509440159596-0249088772ff'),
      },
      {
        id: 'm142',
        name: 'NY Cheesecake',
        description: 'Dense baked cheesecake, graham crust, berry coulis.',
        priceINR: 249,
        veg: true,
        calories: 510,
        allergens: ['gluten', 'dairy', 'eggs'],
        dietary: ['veg'],
        emoji: '🍰',
        imageUrl: u('1567306226416-28f0efdc88ce'),
      },
      {
        id: 'm143',
        name: 'Brownie Sundae',
        description: 'Fudge brownie, ice cream, hot caramel, sea salt.',
        priceINR: 219,
        veg: true,
        calories: 620,
        allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
        dietary: ['veg'],
        emoji: '🍨',
        imageUrl: u('1551024601-bec78aea704b'),
      },
      {
        id: 'm144',
        name: 'Macaron Box (×6)',
        description: 'Pistachio, raspberry, espresso, vanilla, mango, rose.',
        priceINR: 349,
        veg: true,
        calories: 480,
        allergens: ['nuts', 'dairy', 'eggs'],
        dietary: ['veg', 'gluten-free'],
        emoji: '🍪',
        imageUrl: u('1558961363-fa8fdf82db35'),
      },
    ],
    reviews: [],
  },
];

export const MOODS: { id: MoodId; label: string; emoji: string; tagline: string }[] = [
  { id: 'adventurous', label: 'Adventurous', emoji: '🌶️', tagline: 'Try a new cuisine' },
  { id: 'comfort', label: 'Comfort', emoji: '🍜', tagline: 'Hug in a bowl' },
  { id: 'healthy', label: 'Healthy', emoji: '🥗', tagline: 'Light & clean' },
  { id: 'indulgent', label: 'Indulgent', emoji: '🍕', tagline: 'Cheat day vibes' },
  { id: 'spicy', label: 'Spicy', emoji: '🔥', tagline: 'Bring the heat' },
  { id: 'light', label: 'Light', emoji: '🍵', tagline: 'Tea-time crave' },
];

export const CUISINES_FOR_ROULETTE = [
  'Italian',
  'Mexican',
  'Korean',
  'Thai',
  'Japanese',
  'Hyderabadi',
  'American',
  'Middle Eastern',
  'Chinese',
  'South Indian',
  'Vietnamese',
  'Healthy',
];

export type FoodStory = {
  id: string;
  user: string;
  avatarColor: string;
  restaurantId: string;
  caption: string;
  videoEmoji: string;
  likes: number;
  hoursAgo: number;
};

export const FOOD_STORIES: FoodStory[] = [
  {
    id: 's1',
    user: 'Aarav M.',
    avatarColor: '#F59E0B',
    restaurantId: 'r1',
    caption: 'POV: when the biryani is sealed in front of you 🤌',
    videoEmoji: '🍚🔥',
    likes: 1284,
    hoursAgo: 2,
  },
  {
    id: 's2',
    user: 'Mira S.',
    avatarColor: '#22C55E',
    restaurantId: 'r4',
    caption: 'Aburi torch meets miso barley. Lunch goals.',
    videoEmoji: '🍣✨',
    likes: 901,
    hoursAgo: 5,
  },
  {
    id: 's3',
    user: 'Kabir D.',
    avatarColor: '#0EA5E9',
    restaurantId: 'r2',
    caption: 'Cup-and-char pepperoni — that crust crunch is illegal.',
    videoEmoji: '🍕🎶',
    likes: 1810,
    hoursAgo: 1,
  },
  {
    id: 's4',
    user: 'Hana L.',
    avatarColor: '#EF4444',
    restaurantId: 'r6',
    caption: 'Tteokbokki cleared my sinuses, send help 🌶️',
    videoEmoji: '🌶️🔥',
    likes: 1422,
    hoursAgo: 3,
  },
  {
    id: 's5',
    user: 'Zara P.',
    avatarColor: '#A855F7',
    restaurantId: 'r5',
    caption: 'Diablo tacos: humbling but glorious.',
    videoEmoji: '🌮🔥',
    likes: 988,
    hoursAgo: 4,
  },
  {
    id: 's6',
    user: 'Sanya R.',
    avatarColor: '#F472B6',
    restaurantId: 'r13',
    caption: 'Filter kaapi float at midnight = bliss.',
    videoEmoji: '☕️🌙',
    likes: 642,
    hoursAgo: 9,
  },
];

export type Foodie = {
  id: string;
  name: string;
  bio: string;
  avatarColor: string;
  followers: number;
  followingYou?: boolean;
  cuisines: string[];
};

export const FOODIES: Foodie[] = [
  {
    id: 'f1',
    name: 'Aarav M.',
    bio: 'Biryani, kebab, repeat. Hyderabad → Bangalore.',
    avatarColor: '#F59E0B',
    followers: 12480,
    cuisines: ['Hyderabadi', 'Mughlai'],
  },
  {
    id: 'f2',
    name: 'Mira S.',
    bio: 'Macros + miso. Late-night sushi rolls.',
    avatarColor: '#22C55E',
    followers: 8420,
    cuisines: ['Japanese', 'Korean'],
  },
  {
    id: 'f3',
    name: 'Kabir D.',
    bio: 'Pizza purist. Hates pineapple, loves taleggio.',
    avatarColor: '#0EA5E9',
    followers: 9650,
    cuisines: ['Italian', 'European'],
    followingYou: true,
  },
  {
    id: 'f4',
    name: 'Riya K.',
    bio: 'Street food storyteller. ₹100 bites only.',
    avatarColor: '#EC4899',
    followers: 14210,
    cuisines: ['Street food', 'South Indian'],
  },
  {
    id: 'f5',
    name: 'Hana L.',
    bio: 'Spice fiend. Gochujang on everything.',
    avatarColor: '#EF4444',
    followers: 7280,
    cuisines: ['Korean', 'Thai', 'Mexican'],
  },
];

export type Poll = {
  id: string;
  question: string;
  options: { label: string; votes: number }[];
  totalVotes: number;
};

export const POLLS: Poll[] = [
  {
    id: 'p1',
    question: 'Best butter chicken in town?',
    options: [
      { label: 'Biryani Brotherhood', votes: 412 },
      { label: 'Maple & Oats', votes: 213 },
      { label: 'Midnight Dosai Co.', votes: 91 },
    ],
    totalVotes: 716,
  },
  {
    id: 'p2',
    question: 'Pineapple on pizza?',
    options: [
      { label: 'Yes, life is short', votes: 312 },
      { label: 'Absolutely not', votes: 488 },
      { label: 'Only with jalapeños', votes: 96 },
    ],
    totalVotes: 896,
  },
  {
    id: 'p3',
    question: 'Tonight\'s craving?',
    options: [
      { label: 'Spicy noodles', votes: 521 },
      { label: 'Comfort biryani', votes: 412 },
      { label: 'Burger & fries', votes: 367 },
      { label: 'Sushi roll', votes: 284 },
    ],
    totalVotes: 1584,
  },
];

export type Badge = {
  id: string;
  name: string;
  description: string;
  emoji: string;
  unlocked: boolean;
};

export const BADGE_CATALOG: Badge[] = [
  { id: 'b1', name: 'Tried 10 Cuisines', description: 'Spread your palate wide.', emoji: '🌍', unlocked: true },
  { id: 'b2', name: 'Night Owl', description: '5 orders after 11pm.', emoji: '🦉', unlocked: true },
  { id: 'b3', name: 'First Review', description: 'Said something kind.', emoji: '✍️', unlocked: true },
  { id: 'b4', name: 'Spice Champion', description: '10 fire-grade dishes survived.', emoji: '🌶️', unlocked: true },
  { id: 'b5', name: '7-Day Streak', description: 'Order on 7 consecutive days.', emoji: '🔥', unlocked: false },
  { id: 'b6', name: 'Group Chef', description: 'Host 3 group orders.', emoji: '👥', unlocked: false },
  { id: 'b7', name: 'Healthy Hero', description: '20 healthy orders.', emoji: '🥗', unlocked: false },
];

export type LoyaltyTier = 'Bronze' | 'Silver' | 'Gold' | 'Platinum';

export const LOYALTY_TIERS: {
  id: LoyaltyTier;
  threshold: number;
  perks: string[];
  color: string;
}[] = [
  {
    id: 'Bronze',
    threshold: 0,
    perks: ['5% off first weekly order', 'Birthday surprise'],
    color: '#A16207',
  },
  {
    id: 'Silver',
    threshold: 1000,
    perks: ['10% off, free delivery > ₹399', 'Priority support'],
    color: '#94A3B8',
  },
  {
    id: 'Gold',
    threshold: 3000,
    perks: ['15% off, free delivery anytime', 'Early access to drops'],
    color: '#F59E0B',
  },
  {
    id: 'Platinum',
    threshold: 8000,
    perks: ['20% off, premium lane support', 'VIP-only collabs'],
    color: '#A855F7',
  },
];

export const VOICE_QUERY_HINTS = [
  'Spicy pasta under ₹350',
  'Healthy lunch around me',
  'Late-night pizza',
  'Vegan bowls with high protein',
  'Spicy Korean noodles',
  'Burger and fries',
  'Sushi tonight',
  'Surprise me — anything spicy and quick',
];
